### ISSUE TITLE
You did an oopsie

### ISSUE THREAD

**Issue by foxy4096** [himanshuat/qwitter#1]
![image](https://github.com/himanshuat/qwitter/assets/54215788/29a050a4-2035-47f1-b530-11917acf0c53)
See if you can figure it out

![image](https://github.com/himanshuat/qwitter/assets/54215788/ee9c6b6f-1ae8-4eb2-80b3-ea9348524229)
You pushed the database credentials.
Very huge security breach

**Comment by foxy4096** [comment]
I can easily login in the admin panel
![image](https://github.com/himanshuat/qwitter/assets/54215788/10eeefd8-b6ae-43b3-815f-4eb590a1492b)

**Comment by himanshuat** [comment]
Yes, I did know. I will fix it.

**Comment by foxy4096** [comment]
Reset the crednetials

**Comment by himanshuat** [comment]
It's fixed @foxy4096 .
